139 refactor mode
NucleoidAI/IDE pull request #140
Opened 2024-02-08 14:58 UTC by halilcengel

2024-02-08 20:53 UTC, canmingir requested changes

2024-02-08 20:53 UTC, canmingir commented on src/state.js
> +function withPages(nucContext) {
Can you shorten this to `{ api, types, functions }`?

2024-02-08 20:53 UTC, canmingir commented on src/App.jsx
> +    async function InitMode() {
Can you rename to `initMode`?

2024-02-08 20:53 UTC, canmingir commented on src/App.jsx
> +  const InitVfs = (context) => {
Can you rename to `initVfs`?

2024-02-08 20:53 UTC, canmingir commented on src/App.jsx
> +      axios.get(`http://localhost:3000/api/services/${id}/context`),
Didn't we have to use API from config instead of `localhost:3000`?

2024-02-09 11:58 UTC, durulkoca approved these changes

2024-02-09 17:57 UTC, canmingir approved these changes

2024-02-13 14:03 UTC, merged